# Generated by Django 4.0.3 on 2022-03-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('NO_IC', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_namee', models.CharField(max_length=20)),
                ('staff_id', models.IntegerField(null=True)),
                ('nickname', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone_no', models.IntegerField(null=True)),
                ('Email_address', models.CharField(max_length=20)),
                ('birth_ofDate', models.DateField()),
                ('Age', models.IntegerField()),
                ('Country', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Salary', models.IntegerField(null=True)),
                ('Factory_no', models.IntegerField(null=True)),
                ('Badge_id', models.IntegerField(null=True)),
                ('Position', models.CharField(max_length=20)),
                ('Date_join', models.DateTimeField()),
                ('Reporting_to', models.CharField(max_length=20)),
            ],
        ),
    ]
